title: Network Engineers Manifesto
description: A living document for network engineering excellence
baseurl: "/Manifesto"
url: "https://jandahl.github.io"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: false
